[platformio]
core_dir = pio_core/
build_dir = build/
workspace_dir = build/workspace

[env:nano]
platform = atmelavr
framework = arduino
board = nanoatmega328
upload_port = /dev/ttyUSB0
monitor_speed = 115200

; Build options
build_flags =
    -D F_CPU=16000000L
    -D ARDUINO=10805

; Optional: specify programmer for ISP uploads
; upload_protocol = arduino
; upload_protocol = stk500v1
; upload_protocol = usbasp

; Optional: change upload speed (for some bootloaders)
upload_speed = 115200

lib_deps =
    arduino-libraries/Servo@1.1.8
    chris--a/Keypad@3.1.1
