support_material = 1
support_material_style = rectilinear
# cannot - some parts are broken w/o it...
#support_material_buildplate_only = 1
# more fan
bridge_fan_speed = 100
disable_fan_first_layers = 5
fan_always_on = 1
fan_below_layer_time = 100
full_fan_speed_layer = 3
max_fan_speed = 100
min_fan_speed = 100
