solid_infill_every_layers = 1
# author recommends to turn heater off, as some magnets reach Curie temperature and loose grip
bed_temperature_extruder = 0
bed_temperature = 0
first_layer_bed_temperature = 0
